version: '2.20.2'

services:
  postgres:
    image: postgres
    container_name: graphqltestuna
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: graphqltestuna
    ports:
      - '5436:5432'
    volumes:
      - /var/lib/postgresql/data

volumes:
  postgres:
    driver: local